"""Pydantic schemas for Future Scan forward-looking workforce intelligence."""
from typing import List, Optional
from pydantic import BaseModel, Field


class FutureScanRequest(BaseModel):
    role: str = Field(..., description="Role title to forecast, e.g. 'Software Engineer'")
    industry: str = Field(..., description="Industry domain, e.g. 'Technology'")
    region: Optional[str] = Field(default="Global", description="Geographic region, e.g. 'India' or 'Global'")
    horizon: int = Field(default=3, ge=1, le=5, description="Prediction horizon in years (1 to 5)")


class ForecastSkillItem(BaseModel):
    skill: str
    projected_growth: float
    confidence: float
    signal_type: str = Field(..., description="'accelerating', 'emerging', 'stable', 'declining'")


class SkillCombination(BaseModel):
    pair: List[str]
    co_occurrence_multiplier: float
    insight: str


class FutureScanResponse(BaseModel):
    role: str
    industry: str
    region: str
    horizon_years: int
    emerging_skills: List[ForecastSkillItem] = Field(default_factory=list)
    declining_skills: List[ForecastSkillItem] = Field(default_factory=list)
    rising_skill_combinations: List[SkillCombination] = Field(default_factory=list)
    role_evolution_summary: str = Field(default="")
    confidence_score: float = Field(default=0.0)
    supporting_signals: List[str] = Field(default_factory=list)
    is_real_data: bool = Field(default=False, description="True when generated by trained ML models, False in unpopulated baseline")
    message: Optional[str] = Field(default=None, description="Explanation of training pipeline readiness")
